language: csharp
dotnet: 2.1.805
mono: none
os: linux

before_script:
  - dotnet restore
  - dotnet build --no-restore

script:
  - dotnet test -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByFile=\"../main/Core/Database/*\"

after_script:
  - bash <(curl -s https://codecov.io/bash)
