language: csharp
dotnet: 2.1.805
mono: none
os: linux

jobs:
  include:
    - stage: build
      script: dotnet build
      
    - stage: test
      script: dotnet test -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[*]main.Core.Database.Migrations.*%2c[*]main.Core.Domain.Models.*%2c[*]main.Core.Commands%2c[*]main.Core.Configuration%2c[*]main.Core.HttpClient%2c[*]main.Core.CurrentTimeProvider%2c[*]main.Handlers.*"
      after_script: bash <(curl -s https://codecov.io/bash)
    
    - stage: push
      before_script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_OWNER" --password-stdin
      script:
        - cd main
        - docker build --no-cache -t "$DOCKER_OWNER"/samp-discord-bot:latest .
        - docker tag "$DOCKER_OWNER"/samp-discord-bot:latest "$DOCKER_OWNER"/samp-discord-bot:latest
        - docker push "$DOCKER_OWNER"/samp-discord-bot:latest

stages:
  - build
  - test
  - name: push
    if: branch = master AND type != pull_request
